services:
  auth-service:
    container_name: auth-service
    image: auth-service:${TAG_IMAGE}
    build:
        context: ./
        dockerfile: Dockerfile.dev
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./pom.xml
          action: rebuild
    ports:
      - "8000:8000"
    depends_on:
        config-server:
            condition: service_healthy
            restart: true
        auth-db:
            condition: service_healthy
            restart: true
        auth-redis:
            condition: service_healthy
            restart: true

  auth-db:
    container_name: auth-db
    image: mysql:8.0
    ports:
      - "5500:3306"
    volumes:
      - auth-db:/var/lib/mysql
      - ./create-role.sql:/docker-entrypoint-initdb.d/create-role.sql
    env_file:
      - ./.mysql.env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-redis:
    container_name: auth-redis
    image: redis:8.0.3
    ports:
      - "5001:6379"
    volumes:
      - auth-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  auth-db: 
  auth-redis: