spring:
  config:
    import:
    - vault://
  cloud:
    vault:
      scheme: http
      host: vault-server
      port: 8200
      authentication: approle
      app-role:
        role-id: a7719cdf-24b9-6856-c8d6-cf5c0d40f8bb
        # secret-id sẽ hết hạn sau khi hết TTL nên là hãy lấy lại nó
        secret-id: fe9fa591-5450-9e2a-3ce4-c11c4ce95cfd 
        role: auth-approle
        app-role-path: approle/
      database:
        enabled: true
        backend: database
        role: auth-db-role
        username-property: spring.datasource.username
        password-property: spring.datasource.password
